import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ko_KR': {
          // ---------------------- HOME ----------------------
          'login': '로그인',
          'signup': '회원가입',
          'email': '이메일',
          'password': '비밀번호',
          'forgot_password': '비밀번호를 잊으셨나요?',
          'message1': "발음 연습해볼까요? 오늘도 화이팅!",
          'message2': "오늘은 어떤 단어를 배워볼까요?",
          'message3': "오늘도 화이팅!",
          'message4': "꾸준함이 능력! 꾸준히 노력하자!",
          'homeLanguage': '한국어',
          'homeHeaderGuest': '로그인이 필요합니다',
          'speakingAbility1': "발음",
          'speakingAbility2': "높낮이",
          'home_script_title': "대본으로 학습하기",
          'home_script_subtitle': "대본 입력 및 발음 테스트",
          'home_live_script_title': "실시간 발음테스트",
          'home_live_script_subtitle': "실시간 대본 입력 및 발음 테스트",
          'home_chart_title': "진행한 학습",
          // ---------------------- MYPAGE ----------------------
          'mypage_title': '마이페이지',
          'mypage_menu1': '시스템 및 학습 언어 설정',
          'mypage_menu2': '계정 관리',
          'mypage_menu3': '버전 정보',
          'mypage_menu4': '문의',
          'mypage_user_title': '님 반가워요!',
          'mypage_go_login': '로그인',
          // ---------------------- MYPAGE - 언어 설정 ----------------------
          'language_setting_title': '언어 설정',
          'language_setting_system': '시스템 언어',
          'language_setting_learning': '학습 언어',

          'korean': '한국어',
          'english': '영어',
          // ---------------------- Login ----------------------
          'google_login': '구글 계정으로 로그인',
          'google_login_fail_title': '구글 로그인에 실패했습니다',
          'google_login_fail_content': '다시 시도해주세요',
          'signout_fail_title': '회원 탈퇴 실패',
          'signout_fail_content': '회원 탈퇴에 실패했습니다. 다시 시도해주세요.',
          'email_login': '이메일 계정으로 로그인',
          // ---------------------- MYPAGE ----------------------
          'check_network_connection': '네트워크 연결을 확인해주세요',
          'appbar_back': '뒤로',
          ///// --- -밑에서 부터 추가하면 됨
          'appbar_done': '완료',
          'language_setting_snackbar_title': '언어 설정이 변경',
          'language_setting_snackbar_content': '언어 설정이 변경되었습니다.',
          'language_setting_snackbar_fail_title': '언어 설정 변경 실패',
          'language_setting_snackbar_fail_content':
              '언어 설정 변경에 실패했습니다. 다시 시도해주세요.',
          // --------------------- live script ---------------------
          'live_script_title': '실시간 발음 테스트',
          'live_script_hint': '대본을 입력하세요...',
          'analyze_appbar_title': '발음 및 빠르기 분석',
          'analyze_home': '홈으로',
          'analyze_exmaple_title': '발음이 틀린 글씨는 빨간색으로 표시됩니다                ex)',
          'analyze_exmaple_content': '강아지는 ',
          'analyze_exmaple_content2': '뛴다',
          'analyze_exmaple_alert': '문장이 빠르면 빨강, 느리면 보라색 밑줄로 표시됩니다.',
          'profile_account_title': '계정 관리',
          'profile_account_logout': '로그아웃',
          'profile_account_logout_alert_title': '로그아웃',
          'profile_account_logout_alert_content': '정말로 로그아웃하시겠습니까?',
          'profile_account_logout_alert_cancel': '취소',
          'profile_account_signout': '회원 탈퇴',
          'profile_account_signout_alert_title': '회원 탈퇴',
          'profile_account_signout_alert_content': '정말로 탈퇴하시겠습니까?',
          'profile_account_signout_alert_cancel': '취소',
          'profile_account_signout_alert_confirm': '탈퇴',
          'login_fail_snackar_title': '로그인 실패',
          'login_fail_snackar_content': '로그인에 실패했습니다. 다시 시도해주세요.',
          'fail_study_title': '학습 실패',
          'fail_study_content': '다시 녹음해주세요.',
          'fail_study_retry': '다시하기.',
          'fail_study_next_word': '다음 단어',
          'fail_word': '틀린단어 없음',
          'no_data': '데이터가 없습니다.',
          'word_type_2_height': '문장의 높낮이를 참고하세요',
          'word_type_12_height': '아래의 혀, 입술 모양을 따라 말해보세요!',
          'result_title': '결과',
          'result_content': '결과를 확인하세요',
          'pitch': '발음',
          'pitch_null': '너무 빠르거나 느립니다. 다시 녹음해주세요.',
          'accuracy': '정확도',
          'cofirm': '확인',
          // -------------------------------------------------------- 12:56
          'success_study_title': '학습 완료',
          'success_study_content': '다음 단어로 이동하시겠습니까?',
          // 문장 테스트 결과
          'sentence_test_result_title': '문장 테스트 결과',
          'sentence_test_result_sentence': '문장',
          'sentence_test_result_user_sentence': '사용자 발음',
          'sentence_test_result_wrong': '틀린 부분',
          // 알 수 없음
          'unknown': '알 수 없음',
          'sentence_test_result_speed': '속도',
          'sentence_test_result_volume': '볼륨',
          'sentence_test_result_pitch': '변동성',
          'sentence_test_result_stability': '일정함',
          'sentence_test_result_pitch_high': '변동 폭 큼',
          'next': '다음',
          'sentence_test_result_speed_very_slow': '엄청 느림',
          'sentence_test_result_speed_slow': '느림',
          'sentence_test_result_speed_normal': '보통',
          'sentence_test_result_speed_fast': '빠름',
          'sentence_test_result_speed_very_fast': '엄청 빠름',
          'sound_pitch': '목소리 높이',
          'sound_pitch_stability': '변동 일정',
          'sound_pitch_high': '변동',
          'sound_speed': '속도',
          'study_main_title_1': '음소 교정',
          'study_main_subtitle_1': '음소 교정 및 발음 테스트',
          'study_main_title_2': '단어 교정',
          'study_main_subtitle_2': '단어 교정 및 발음 테스트',
          'study_main_title_3': '문장 교정',
          'study_main_subtitle_3': '문장 교정 및 발음 테스트',
          'study_main_title_4': '문단 교정',
          'study_main_subtitle_4': '대본 입력 및 발음 테스트',
          'row_card_badge_1': "음소",
          'row_card_badge_2': "단어",
          'row_card_badge_3': "문장",
          'row_card_badge_4': "문단",
          'go_study': '학습 하러가기',
          'no_study_record': '등록된 학습 기록이 없습니다.',
          'voice_recognition': '음성 인식을 통해 발음이 여기에 표시됩니다...',
          'email_signup': '이메일 회원가입',
          'email_login_2': '이메일 로그인',
          'go_signup': '회원가입 하러가기',
          'signup_fail_title': '회원가입 실패',
          'signup_fail_content': '회원가입에 실패했습니다. 다시 시도해주세요.',
          'email_address': '이메일 주소를 입력해주세요',
          'password_input': '비밀번호를 입력해주세요',
          'email_address_input': '올바른 이메일 주소를 입력해주세요',
          'password_input_2': '비밀번호는 10자리 이상이어야 합니다.',
          'password_input_3': '비밀번호는 문자와 숫자가 섞여있어야 합니다.',
          'study_main_title_5': '문단 교정',
          // bottomNavigationBar
          'navi_learning': '학습페이지',
          'navi_mypage': '마이페이지',
        },
        'en_US': {
          // ---------------------- HOME ----------------------
          'login': 'Login',
          'signup': 'Sign Up',
          'email': 'Email',
          'password': 'Password',
          'forgot_password': 'Forgot Password?',
          'message1': "Let's practice pronunciation! Fighting today too!",
          'message2': "What word shall we learn today?",
          'message3': "Fighting today too!",
          'message4': "Consistency is ability! Let's make steady efforts!",
          'homeLanguage': 'English',
          'homeHeaderGuest': 'Login required',
          'speakingAbility1': "Pronun",
          'speakingAbility2': "Pitch",
          'home_script_title': "Learn with Scripts",
          'home_script_subtitle': "Script test",
          'home_live_script_title': "live Test",
          'home_live_script_subtitle': "live script test",
          'home_chart_title': "Progressed Learning",
          // ---------------------- MYPAGE ----------------------
          'mypage_title': 'My Page',
          'mypage_menu1': 'System and Learning Language Settings',
          'mypage_menu2': 'Account Management',
          'mypage_menu3': 'Version Information',
          'mypage_menu4': 'Contact',
          'mypage_user_title': 'Hello,',
          'mypage_go_login': 'Login',
          // ---------------------- MYPAGE - Language Settings ----------------------
          'language_setting_title': 'Language Settings',
          'language_setting_system': 'System Language',
          'language_setting_learning': 'Learning Language',
          'korean': 'Korean',
          'english': 'English',
          // ---------------------- Login ----------------------
          'google_login': 'Login with Google Account',
          'google_login_fail_title': 'Google Login Failed',
          'google_login_fail_content': 'Please try again.',
          'signout_fail_title': 'Sign Out Failed',
          'signout_fail_content': 'Failed to sign out. Please try again.',
          'email_login': 'Login with Email Account',
          // ---------------------- MYPAGE ----------------------
          'check_network_connection': 'Please check your network connection',
          'appbar_back': 'Back',
          // ---------------------- Additional Translations ----------------------
          'appbar_done': 'Done',
          'language_setting_snackbar_title': 'Language Setting Changed',
          'language_setting_snackbar_content':
              'Language setting has been changed.',
          'language_setting_snackbar_fail_title':
              'Language Setting Change Failed',
          'language_setting_snackbar_fail_content':
              'Failed to change language setting. Please try again.',
          // --------------------- Live Script ---------------------
          'live_script_title': 'Real-time Pronunciation Test',
          'live_script_hint': 'Enter the script...',
          'analyze_appbar_title': 'Pronunciation and Speed Analysis',
          'analyze_home': 'Back to Home',
          'analyze_exmaple_title':
              'Incorrect pronunciation is highlighted in red, for example:',
          'analyze_exmaple_content': 'The dog ',
          'analyze_exmaple_content2': 'runs',
          'analyze_exmaple_alert':
              'If the sentence is fast, it will be marked with a red underline; if it is slow, with a purple underline.',
          'profile_account_title': 'Account Management',
          'profile_account_logout': 'Logout',
          'profile_account_logout_alert_title': 'Logout',
          'profile_account_logout_alert_content':
              'Are you sure you want to log out?',
          'profile_account_logout_alert_cancel': 'Cancel',
          'profile_account_signout': 'Sign Out',
          'profile_account_signout_alert_title': 'Sign Out',
          'profile_account_signout_alert_content':
              'Are you sure you want to sign out?',
          'profile_account_signout_alert_cancel': 'Cancel',
          'profile_account_signout_alert_confirm': 'Sign Out',
          'login_fail_snackar_title': 'Login Failed',
          'login_fail_snackar_content': 'Login failed. Please try again.',
          // Fail Study
          'fail_study_title': 'Study Failed',
          'fail_study_content': 'Please record again.',
          'fail_study_retry': 'Retry',
          'fail_study_next_word': 'Next Word',
          // Fail Word
          'fail_word': 'No Incorrect Words',
          'no_data': 'No Data Available.',
          // Word Types
          'word_type_2_height': 'Refer to the pitch of the sentence.',
          'word_type_12_height': 'Speak following the tongue/lip shapes below!',
          // Results
          'result_title': 'Results',
          'result_content': 'Check your results',
          'pitch': 'Pronunciation',
          'pitch_null': 'Too fast or too slow. Please record again.',
          'accuracy': 'Accuracy',
          'confirm': 'Confirm',
          ////// ------------------------------------------------ 12:56
          ///         // Success Study
          'success_study_title': 'Study Completed',
          'success_study_content':
              'Would you like to move on to the next word?',
          // Sentence Test Result
          'sentence_test_result_title': 'Sentence Test Result',
          'sentence_test_result_sentence': 'Sentence',
          'sentence_test_result_user_sentence': 'User Pronunciation',
          'sentence_test_result_wrong': 'Incorrect Part',
          // Unknown
          'unknown': 'Unknown',
          'sentence_test_result_speed': 'Speed',
          'sentence_test_result_volume': 'Volume',
          'sentence_test_result_pitch': 'Pitch',
          'sentence_test_result_stability': 'Stability',
          'sentence_test_result_pitch_high': 'High Variability',
          'next': 'Next',
          'sentence_test_result_speed_very_slow': 'Very Slow',
          'sentence_test_result_speed_slow': 'Slow',
          'sentence_test_result_speed_normal': 'Normal',
          'sentence_test_result_speed_fast': 'Fast',
          'sentence_test_result_speed_very_fast': 'Very Fast',
          'sound_pitch': 'Voice Pitch',
          'sound_pitch_stability': 'Pitch Stability',
          'sound_pitch_high': 'High Variability',
          'sound_speed': 'Speed',
          // Study Main Titles and Subtitles
          'study_main_title_1': 'Phoneme',
          'study_main_subtitle_1': 'Phoneme Correction Test',
          'study_main_title_2': 'Word',
          'study_main_subtitle_2': 'Word Correction Test',
          'study_main_title_3': 'Sentence',
          'study_main_subtitle_3': 'Sentence Correction Test',
          'study_main_title_4': 'Paragraph',
          'study_main_subtitle_4': 'Script Correction Test',
          'row_card_badge_1': 'Phoneme',
          'row_card_badge_2': 'Word',
          'row_card_badge_3': 'Sentence',
          'row_card_badge_4': 'Paragraph',
          'go_study': 'Go to Study',
          'no_study_record': 'No registered study records.',
          'voice_recognition':
              'Pronunciation through voice recognition will be displayed here...',
          // Email Signup and Login
          'email_signup': 'Email Sign Up',
          'email_login_2': 'Email Login',
          'go_signup': 'Go to Sign Up',
          'signup_fail_title': 'Sign Up Failed',
          'signup_fail_content': 'Failed to sign up. Please try again.',
          'email_address': 'Please enter your email address',
          'password_input': 'Please enter your password',
          'email_address_input': 'Please enter a valid email address',
          'password_input_2': 'Password must be at least 10 characters.',
          'password_input_3':
              'Password must contain a mix of letters and numbers.',
          'study_main_title_5': 'Paragraph Correction',
          // navi
          'navi_learning': 'Learning',
          'navi_mypage': 'Profile',
        },
      };
}
